export const brands = [
    {
        id:1,
        name:"TATA",
        logo:"../Brands/TATA.png"
    },
    {
        id:2,
        name:"SUZUKI",
        logo:"../Brands/SUZUKI.png"
    },
    {
        id:3,
        name:"HYUNDAI",
        logo:"../Brands/HYUNDAI.png"
    },
    {
        id:4,
        name:"TOYOTA",
        logo:"../Brands/TOYOTA.png"
    },
    {
        id:5,
        name:"MG",
        logo:"../Brands/MG.png"
    },
    {
        id:6,
        name:"HONDA",
        logo:"../Brands/HONDA.png"
    },
    {
        id:7,
        name:"SKODA",
        logo:"../Brands/SKODA.png"
    },
    {
        id:8,
        name:"NISSAN",
        logo:"../Brands/NISSAN.png"
    },
    {
        id:9,
        name:"VOLKSWAGON",
        logo:"../Brands/VOLKSWAGON.png"
    },
    {
        id:10,
        name:"JEEP",
        logo:"../Brands/JEEP.png"
    },
    {
        id:11,
        name:"CITROEN",
        logo:"../Brands/CITROEN.png"
    },
    {
        id:12,
        name:"KIA",
        logo:"../Brands/KIA.png"
    }
]